### PR TITLE
Working changes for bitbucket-cmd

### PR DESCRIPTION
**Pull request by palashkulsh**
Current pull request has following features
1. repo wise authentication and reviewer support.
2. merge,approve,decline,create,diff and patch pull request.
3. visually appealing pr list output with toggling colors.
4. current branch indicator for source branch in pr list option. [star and grey color]
5. if no source or destination branch is specified then create the PR from current branch and master.
6. now PR creation is as follows.

- pull the destination branch from origin
- merge destination branch to source branch
- push the source branch to remote
- then create pull request.
- fail if any of the above git steps fail. In this way merge conflicted PR wont be created. PR creation will fail if there is any merge conflict.
7. Suitable changes to readme.

### CODE REVIEW

**Comment by hxuanhung** [comment]
@danshumaker Do you have time to look at this PR?

**Comment by danshumaker** [comment]
Why not! Let's go for it! Done and done.

**Comment by danshumaker** [comment]
Hmm,  that's too bad, it looks like after merging that branch it has broken the code. @palashkulsh Now I'm getting 401 messages.

**Comment by danshumaker** [comment]
I'm going to revert that commit because I do not believe in storing the actual passwords in the config file.  It use to be a token in the config file and now it's the actual password.  I apologize for not testing this before I merged it.

**Comment by danshumaker** [comment]
It's reverted and Palash's code is now on the palash_new_start branch if you want to experiment with it.  I'll try to debug it as well , time permitting.

**Comment by palashkulsh** [comment]
Dan , I've added a plethora of functionalities in my fork, If you can drop a hint of corrections you would like. I can raise a PR for them here.

**Pull request merged**
